### ISSUE TITLE
[Web] Can't connect sdk

### ISSUE THREAD

**Issue by lejard-h** [Dalk-io/sdk#2]
On web platform.

Tried to setup my project.

```dart
sdk = DalkSdk(PROJECT_ID, user);
await sdk.connect();
```

Error: `Parameter "signature" for method "registerUser" must be a string, but was null.`

I am not using Secure connection settings. (I can't toggle checkbox)

**Comment by jaumard** [comment]
should be ok on 0.0.3 :) 

we're checking the checkbox
